/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Deloam Kitty
 */
public class janelaPrinc extends javax.swing.JFrame {

    /**
     * Creates new form janelaPrinc
     */
    public janelaPrinc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        areaDeTrabalho = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPrincipal = new javax.swing.JMenu();
        jMenuItemCadastros = new javax.swing.JMenuItem();
        jMenuItemConsultas = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuClientes = new javax.swing.JMenu();
        jMenuItemCadClientes = new javax.swing.JMenuItem();
        jMenuItemConCliente = new javax.swing.JMenuItem();
        jMenuFornecedor = new javax.swing.JMenu();
        jMenuItemCadForne = new javax.swing.JMenuItem();
        jMenuItemConForne = new javax.swing.JMenuItem();
        jMenuProdutos = new javax.swing.JMenu();
        jMenuItemCadProduto = new javax.swing.JMenuItem();
        jMenuItemConProduto = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        areaDeTrabalho.setAutoscrolls(true);

        jLabel1.setText("Build Verson 1.0.0.0");

        javax.swing.GroupLayout areaDeTrabalhoLayout = new javax.swing.GroupLayout(areaDeTrabalho);
        areaDeTrabalho.setLayout(areaDeTrabalhoLayout);
        areaDeTrabalhoLayout.setHorizontalGroup(
            areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, areaDeTrabalhoLayout.createSequentialGroup()
                .addContainerGap(518, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        areaDeTrabalhoLayout.setVerticalGroup(
            areaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, areaDeTrabalhoLayout.createSequentialGroup()
                .addContainerGap(344, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        areaDeTrabalho.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(areaDeTrabalho);

        jMenuPrincipal.setText("Menu");

        jMenuItemCadastros.setText("cadastros");
        jMenuItemCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrosActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(jMenuItemCadastros);

        jMenuItemConsultas.setText("consulta");
        jMenuPrincipal.add(jMenuItemConsultas);

        jMenuItemSair.setText("sair");
        jMenuPrincipal.add(jMenuItemSair);

        jMenuBar1.add(jMenuPrincipal);

        jMenuEditar.setText("Editar");
        jMenuBar1.add(jMenuEditar);

        jMenuClientes.setText("Clientes");

        jMenuItemCadClientes.setText("cadastrar cliente");
        jMenuClientes.add(jMenuItemCadClientes);

        jMenuItemConCliente.setText("consultar clientes");
        jMenuClientes.add(jMenuItemConCliente);

        jMenuBar1.add(jMenuClientes);

        jMenuFornecedor.setText("Fornecedor");

        jMenuItemCadForne.setText("cadastrar fornecedor");
        jMenuFornecedor.add(jMenuItemCadForne);

        jMenuItemConForne.setText("consultar fornecedores");
        jMenuFornecedor.add(jMenuItemConForne);

        jMenuBar1.add(jMenuFornecedor);

        jMenuProdutos.setText("Produtos");

        jMenuItemCadProduto.setText("cadastrar produtos");
        jMenuProdutos.add(jMenuItemCadProduto);

        jMenuItemConProduto.setText("consultar produtos");
        jMenuProdutos.add(jMenuItemConProduto);

        jMenuBar1.add(jMenuProdutos);

        jMenuSobre.setText("sobre");
        jMenuBar1.add(jMenuSobre);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrosActionPerformed
        Cadastros form;
        form = new Cadastros();
        form.setVisible(true);
        areaDeTrabalho.add(form);
       
    }//GEN-LAST:event_jMenuItemCadastrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janelaPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janelaPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janelaPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janelaPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new janelaPrinc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaDeTrabalho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenu jMenuFornecedor;
    private javax.swing.JMenuItem jMenuItemCadClientes;
    private javax.swing.JMenuItem jMenuItemCadForne;
    private javax.swing.JMenuItem jMenuItemCadProduto;
    private javax.swing.JMenuItem jMenuItemCadastros;
    private javax.swing.JMenuItem jMenuItemConCliente;
    private javax.swing.JMenuItem jMenuItemConForne;
    private javax.swing.JMenuItem jMenuItemConProduto;
    private javax.swing.JMenuItem jMenuItemConsultas;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuPrincipal;
    private javax.swing.JMenu jMenuProdutos;
    private javax.swing.JMenu jMenuSobre;
    // End of variables declaration//GEN-END:variables
}
